### ISSUE TITLE
Question: How does consistent hash interact with backup upstreams?

### ISSUE THREAD

**Issue by sheldonkwok** [replay/ngx_http_consistent_hash#8]
How does consistent hash interact with backup upstreams?

If the target server for a hashed path is down, does nginx use a backup server/another server in the upstream block? Or, does it just respond with a 5XX error? If it proxies to another server, is the new server now marked for consistent hashing of the path? 

Thank you!

**Comment by newjunwei** [comment]
It just respond with a 5XX error when i tested.
